name: Deploy Bot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create private key file
      run: |
        echo "${{ secrets.KEY }}" | base64 -d > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy and Start Bot on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@51.21.111.227 "
          cd /home/ubuntu/Top-bot && 
          git pull && 
          nohup node multibot.js > bot.log 2>&1 &
        "
