name: Deploy Bot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@51.21.111.227 << 'EOF'
          pm2 stop all || true
          cd Top-bot
          git pull origin main
          npm install
          pm2 start multibot.js --name topbot
        EOF
